Repository joong8812/mooyaho, pull requests merged in 2022-03, with the labels that each got.

#20 수정 및 추가: [백엔드] settings 파일 수정, 유저 모델 및 기능 작성
  config/settings.py
  config/urls.py
  user/admin.py
  user/urls.py
  user/user_models.py
  user/user_service.py
Labels: enhancement

#24 [백엔드] User 모델 수정, Post 모델 정의
  post/post_models.py
  user/user_models.py
Labels: enhancement

#31 추가: Mountain url 연결, 산 추천 메인 페이지 로드 함수 추가
  mountain/urls.py
  mountain/views.py
  post/models.py
  post/post_models.py
  post/post_service.py
  post/urls.py
  post/views.py
  templates/post/detail.html
  templates/post/new.html
  templates/post/posts.html
  user/models.py
  user/user_models.py
  user/views.py
Labels: enhancement

#34 [백엔드] 수정: 포스팅 페이지 HTML 파일, Post모델, help앱 url 수정
  help/urls.py
  post/post_models.py
  templates/post/detail.html
  templates/post/posts.html
Labels: enhancement

#37 [백엔드] 수정: url 관련 내용 수정 반영 요청
  config/urls.py
  post/urls.py
  templates/base.html
  user/urls.py
Labels: enhancement

#40 [백엔드] 추가: 마이페이지 접속 url, 기능 함수 추가
  user/urls.py
  user/user_service.py
Labels: enhancement

#46 [백엔드] Comment app 관련 설정 추가
  comment/__init__.py
  comment/admin.py
  comment/apps.py
  comment/comment_models.py
  comment/comment_service.py
  comment/tests.py
  comment/urls.py
  config/settings.py
  config/urls.py
  post/post_service.py
  post/urls.py
Labels: enhancement

#60 [백엔드] 글 수정 및 삭제 기능 함수, url 추가
  post/post_service.py
  post/urls.py
Labels: enhancement

#62 [백엔드] 글 수정 및 삭제 글쓴이 정보 확인 코드 수정
  post/post_service.py
Labels: enhancement

#65 [백엔드] 글 삭제 관련 설정 수정, 유저 프로필 사진 필드 수정
  post/post_service.py
  user/user_models.py
Labels: bug

#66 [백엔드] User, Post 모델 수정, 포스팅 삭제 및 댓글 표시 설정 수정
  post/post_models.py
  post/post_service.py
  user/user_models.py
Labels: bug, enhancement

#69 [백엔드] 추가: 글 상세 페이지 좋아요, 신고 기능 코드 구현 1차
  post/post_models.py
  post/post_service.py
  post/urls.py
Labels: enhancement

#73 [백엔드] 추가: 마이페이지 유저 게시글 및 좋아요 글 불러오기 추가
  user/user_service.py
Labels: enhancement

#74 [백엔드] 수정: 포스팅 업로드 이미지 파일명 설정 수정
  post/post_models.py
Labels: bug

#75 [백엔드] 수정: 마이페이지에서 삭제 처리된 글 안보이게 처리
  user/user_service.py
Labels: bug

#76 [백엔드] 수정: gitignore, settings 파일 일부 내용 수정
  .gitignore
  config/settings.py
Labels: bug

#78 [백엔드] 좋아요 기능 구현 1차
  post/post_service.py
  post/static/js/posts.js
  templates/post/detail.html
Labels: enhancement

#80 공지사항 글쓰기 버튼, 글쓰기 기능, 글 목록 표시 구현.
  help/urls.py
  help/views.py
  templates/help/help.html
  templates/help/notice.html
  templates/help/post_notice.html
  templates/help/review.html
Labels: enhancement

#81 [백엔드] 기능 추가: 댓글 작성 기능 구현
  comment/comment_service.py
  comment/urls.py
  post/post_service.py
  post/static/js/posts.js
  templates/post/detail.html
Labels: enhancement

#84 [백엔드] 수정: 글쓰기 페이지 등록 버튼 연결 url 수정
  templates/post/new.html
Labels: bug

#85 [백엔드] 댓글 삭제 기능 관련 파일 수정 및 코드 추가
  comment/comment_service.py
  comment/urls.py
  config/settings.py
  post/static/js/posts.js
  templates/post/detail.html
Labels: enhancement

#87 [백엔드] 댓글, 신고 기능 수정
  comment/comment_service.py
  post/post_service.py
  post/static/js/posts.js
  templates/post/detail.html
Labels: enhancement

#89 [백엔드] 수정 및 추가: 포스팅, 댓글, 좋아요 기능 일부 수정
  comment/comment_service.py
  comment/urls.py
  post/post_form.py
  post/post_models.py
  post/post_service.py
  post/static/js/posts.js
  templates/post/detail.html
  templates/post/new.html
Labels: bug, enhancement

#97 [프론트엔드&백엔드] 수정 및 추가: 신고 글 id값 저장 추가, 글 작성자 댓글 기능 수정
  post/post_service.py
  templates/post/detail.html
Labels: bug, enhancement

#110 [프론트엔드&백엔드] 수정 및 추가: 원격 repo 최신화, 글 수정 및 삭제 기능 구현
  post/post_service.py
  post/static/js/posts.js
  post/urls.py
  templates/post/new.html
Labels: bug, enhancement

#117 [프론트엔드&백엔드] 수정 및 반영: 좋아요 버튼 비동기 색상 변경 구현, 기존 별점 가져오기 구현
  config/settings.py
  post/static/js/posts.js
  templates/post/new.html
Labels: bug, enhancement

#119 [백엔드] 수정: 닉네임 길이 제한 증가로 user model 필드 수정
  user/user_models.py
Labels: bug

#122 [백엔드] 추가: 유저 요청 데이터 제한 용량 증가 위한 파일 추가
  .platform/myconf.config
  .platform/nginx/conf.d/proxy.conf
Labels: bug

#124 [백엔드] 수정 및 삭제: 불필요한 코드 및 요소 삭제
  post/admin.py
  templates/post/detail.html
  templates/post/new.html
Labels: bug

#127 [프론트엔드] 수정 및 추가: 포스팅 전체, 상세 페이지 css 파일 분리
  post/static/css/posts_all.css
  templates/post/posts.html
Labels: bug

#131 [프론트엔드&백엔드] 수정 및 추가: 유저 기본 프로필 이미지 관련 내용 반영
  templates/mountain/main.html
  user/static/images/default_profile_img.jpg
  user/user_models.py
Labels: bug, enhancement

#135 [프론트엔드] 수정: 전체 글 페이지 프로필 사진 표시되게 수정
  templates/post/posts.html
Labels: bug

#136 [백엔드] 수정 및 추가: 유저 프로필 사진 default 값 설정, 주석 추가
  post/post_service.py
  user/user_models.py
Labels: bug, enhancement

#142 [프론트엔드&백엔드] 수정 및 추가: 글 쓰기 사진 등록 오류 관련 코드 수정, 에러 메시지 추가
  post/post_service.py
  post/static/css/posts.css
  templates/post/new.html
Labels: bug

#143 [프론트엔드] 수정: 글 쓰기 폼 에러 메시지 표시 수정
  post/static/css/posts.css
  templates/post/new.html
Labels: bug

#144 [프론트엔드&백엔드] 수정 및 추가: 댓글 내용 있을 때만 게시 버튼 활성화로 수정
  comment/comment_service.py
  post/static/js/posts.js
  templates/post/detail.html
Labels: enhancement

#145 [백엔드] 수정 및 추가: 각 모델 클래스 관리자 페이지에 등록
  help/admin.py
  mountain/admin.py
  user/admin.py
Labels: enhancement

#156 [백엔드] 수정: 각 모델이 관리자 페이지에서 표시되는 형식 수정
  comment/comment_models.py
  help/models.py
  mountain/models.py
  user/user_models.py
Labels: enhancement
