Repository joong8812/mooyaho, pull requests merged in 2022-04, with the labels that each got.

#161 둘러보기 기능(비로그인) 구현 - 로그인, 전체산, 산상세
  mountain/views.py
  templates/user/login.html
  user/static/css/user/login.css
Labels: enhancement

#163 수정 - 비회원일경우 기능 수정
  help/views.py
  mountain/views.py
  templates/base.html
Labels: enhancement

#162 둘러보기 기능(비로그인) 구현 - 고객센터
  help/views.py
Labels: enhancement

#165 게시물 상세페이지 들어갈때 userviewlog에 기록 남기기
  post/post_service.py
  user/user_models.py
Labels: bug, enhancement

#168 [둘러보기] 안내 메시지 구현
  mountain/views.py
  templates/base.html
  user/static/js/base.js
Labels: enhancement

#178 [둘러보기] 게스트 유무 판단 값 수정(파이썬 boolean값이 True 이기 때문)
  user/static/js/base.js
Labels: bug

#180 [산상세] 맛집 클릭 시 새 탭or새 창에서 열리도록 수정
  mountain/static/js/mountain/mountains_detail.js
Labels: enhancement

#186 [프론트엔드&백엔드] 피드백 반영: 회원 탈퇴 기능 추가
  templates/user/delete_account_form.html
  templates/user/mypage.html
  user/migrations/0002_mooyahouser_disabled_reason.py
  user/migrations/0003_alter_mooyahouser_disabled_reason.py
  user/static/css/user/delete_account_form.css
  user/static/css/user/mypage.css
  user/static/js/user/delete_account.js
  user/urls.py
  user/user_models.py
  user/user_service.py
Labels: enhancement

#183 [회원가입] 비밀번호 제약조건 추가
  user/static/js/user/signup.js
Labels: enhancement

#194 [산 상세] 산 이미지와 산이름 겹치지 않게 재배치
  mountain/static/css/mountain/mountains_detail.css
Labels: bug

#195 [마이페이지] 헤더 검색 버튼 클릭시 본문 div 사라짐 해결
  templates/base.html
  user/static/css/user/mypage.css
  user/static/js/base.js
Labels: bug

#200 [포스팅 페이지] 수정: 포스팅 페이지, 헤더 클릭 가능 요소 포인터 활성화
  post/static/css/post_detail.css
  post/static/css/posts.css
  post/static/css/posts_all.css
  post/static/js/posts.js
  templates/base.html
  templates/post/detail.html
Labels: enhancement

#196 추가: 로고누르면 main페이지 이동, 산이름 누르면 산상세페이지 이동
  post/static/css/posts_all.css
  templates/base.html
  templates/post/detail.html
  templates/post/posts.html
Labels: enhancement

#199 add - 산 "province" 지역별 분류 필드 추가
  mountain/migrations/0001_initial.py
  mountain/migrations/0002_mountain_province.py
  mountain/migrations/__init__.py
  mountain/models.py
  templates/base.html
  user/user_service.py
Labels: enhancement

#206 [산 상세] 첫 등산로는 prev, 마지막에선 next 버튼 안보이게 / 등산로 데이터 없는 경우 처리
  mountain/static/js/mountain/mountains_detail.js
Labels: enhancement

#211 [회원가입] 이메일 아이디에 마침표 포함 하도록 수정
  user/static/js/user/signup.js
Labels: bug

#215 footer 아이콘에 현재 페이지 표시
  templates/base.html
  user/static/css/base.css
  user/static/js/base.js
Labels: enhancement
